//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge.CubeSummationNS.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CubeSummationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CubeSummationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challenge.CubeSummationNS.Model.Resources.CubeSummationResources", typeof(CubeSummationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de casos de prueba debe ser entre 1 y 50..
        /// </summary>
        public static string Error_Cantidad_CasosPruebas {
            get {
                return ResourceManager.GetString("Error_Cantidad_CasosPruebas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación &apos;UPDATE&apos; solo permite seis (6) datos de entrada..
        /// </summary>
        public static string Error_Cantidad_Datos_OperacionQuery {
            get {
                return ResourceManager.GetString("Error_Cantidad_Datos_OperacionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación &apos;UPDATE&apos; solo permite cuatro (4) datos de entrada..
        /// </summary>
        public static string Error_Cantidad_Datos_OperacionUpdate {
            get {
                return ResourceManager.GetString("Error_Cantidad_Datos_OperacionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las coordenadas deben de ser menor o igual que el tamaño de la matriz..
        /// </summary>
        public static string Error_Coordenadas {
            get {
                return ResourceManager.GetString("Error_Coordenadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de entrada deben contener valor..
        /// </summary>
        public static string Error_Datos_Entrada_Vacio {
            get {
                return ResourceManager.GetString("Error_Datos_Entrada_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado. Por favor contacte al personal de soporte..
        /// </summary>
        public static string Error_Mensaje_Default {
            get {
                return ResourceManager.GetString("Error_Mensaje_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño de la matriz debe estar entre 1 y 100..
        /// </summary>
        public static string Error_Tamano_Matriz {
            get {
                return ResourceManager.GetString("Error_Tamano_Matriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de operaciones debe estar entre 1 y 1000..
        /// </summary>
        public static string Error_Tamano_Operaciones {
            get {
                return ResourceManager.GetString("Error_Tamano_Operaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los valores válidos para actualizar una posición del cubo oscila entre 10^9 y 10^-9..
        /// </summary>
        public static string Error_Valores_Máximos_OperacionUpdate {
            get {
                return ResourceManager.GetString("Error_Valores_Máximos_OperacionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación Exitosa..
        /// </summary>
        public static string Mensaje_Operacion_Exitosa {
            get {
                return ResourceManager.GetString("Mensaje_Operacion_Exitosa", resourceCulture);
            }
        }
    }
}
